package org.flexlabs.widgets.dualbattery.storage;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table BATTERY_LEVELS.
 */
public class BatteryLevels {

    private Long id;
    /** Not-null value. */
    private java.util.Date time;
    private int status;
    private int level;
    private int dockStatus;
    private Integer dockLevel;
    private boolean screenOn;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BatteryLevels() {
    }

    public BatteryLevels(Long id) {
        this.id = id;
    }

    public BatteryLevels(Long id, java.util.Date time, int status, int level, int dockStatus, Integer dockLevel, boolean screenOn) {
        this.id = id;
        this.time = time;
        this.status = status;
        this.level = level;
        this.dockStatus = dockStatus;
        this.dockLevel = dockLevel;
        this.screenOn = screenOn;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public java.util.Date getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }

    public int getDockStatus() {
        return dockStatus;
    }

    public void setDockStatus(int dockStatus) {
        this.dockStatus = dockStatus;
    }

    public Integer getDockLevel() {
        return dockLevel;
    }

    public void setDockLevel(Integer dockLevel) {
        this.dockLevel = dockLevel;
    }

    public boolean getScreenOn() {
        return screenOn;
    }

    public void setScreenOn(boolean screenOn) {
        this.screenOn = screenOn;
    }

    // KEEP METHODS - put your custom methods here
    public static BatteryLevels createNew(DaoSession session, int status, int level, int dockStatus, Integer dockLevel, boolean screenOn) {
        BatteryLevels batteryLevel = new BatteryLevels(null, new java.util.Date(), status, level, dockStatus, dockLevel, screenOn);
        session.getBatteryLevelsDao().insert(batteryLevel);
        return batteryLevel;
    }
    // KEEP METHODS END

}
