package org.flexlabs.widgets.dualbattery.storage;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.flexlabs.widgets.dualbattery.storage.BatteryLevels;

import org.flexlabs.widgets.dualbattery.storage.BatteryLevelsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig batteryLevelsDaoConfig;

    private final BatteryLevelsDao batteryLevelsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        batteryLevelsDaoConfig = daoConfigMap.get(BatteryLevelsDao.class).clone();
        batteryLevelsDaoConfig.initIdentityScope(type);

        batteryLevelsDao = new BatteryLevelsDao(batteryLevelsDaoConfig, this);

        registerDao(BatteryLevels.class, batteryLevelsDao);
    }
    
    public void clear() {
        batteryLevelsDaoConfig.getIdentityScope().clear();
    }

    public BatteryLevelsDao getBatteryLevelsDao() {
        return batteryLevelsDao;
    }

}
