package org.flexlabs.widgets.dualbattery.storage;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SCREEN_STATES.
 */
public class ScreenStates {

    private Long id;
    /** Not-null value. */
    private java.util.Date time;
    private boolean screenOn;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ScreenStates() {
    }

    public ScreenStates(Long id) {
        this.id = id;
    }

    public ScreenStates(Long id, java.util.Date time, boolean screenOn) {
        this.id = id;
        this.time = time;
        this.screenOn = screenOn;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public java.util.Date getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public boolean getScreenOn() {
        return screenOn;
    }

    public void setScreenOn(boolean screenOn) {
        this.screenOn = screenOn;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
